### ISSUE TITLE
Incorrect paid amount shown in transaction report

### ISSUE THREAD

**Issue by ledger123** [ledger123/runmyaccounts#58] opened 2016-03-23 03:54 UTC
This occurs when the invoice amount and paid amount difference is exactly that of tax for that invoice.

**Comment by ledger123** [comment] 2016-03-23 06:52
This has been fixed.

**Comment by sweitmann** [comment] 2016-03-24 02:10
Hi Armaghan,

Thanks. Tested and confirmed. Closing this ticket now.

Regards

**Comment by sweitmann** [comment] 2016-03-24 02:10
Actually, you will have to close this one, since you opened it :)

**Closed** 2016-03-24 02:55 UTC
