### ISSUE TITLE
Release 'Export--GoBD' and 'Export--'Preliminary VAT Return'

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#277] opened 2021-11-04 13:02 UTC
Hi Armaghan, 

As discussed in our call today we need to get these features up and running on our RMA clone. 

Our server clone has been updated with the following commands:

emerge dev-perl/App-cpanminus
emerge dev-perl/XML-Parser
emerge dev-perl/XML-Twig

cpanm Mojo::Pg
cpanm OpenOffice::OODoc
cpanm File::Type GD::Graph
cd /usr/local/lib64/perl5/5.30.3/
chmod -R 755 File

chmod -R 755 sql-ledger/mojo/
chmod -R 755 sql-ledger/css/*.css

But for some reason it's still not working. Grateful if you could look into this and help me find the reason. 

I have switched to branch 198_vat_return_and_gobd_export_feature and when I try to run 'Export--GoBD' or 'Export--Preliminary VAT Return' feature, to start with I get the 'Not logged in error message'.

Regards

**Comment by ledger123** [comment] 2021-11-08 05:42
I was able to make it work this way:

(1) "Not logged in" message is because RMA code is removing sql-ledger password after authentication and using its own application authentication. To do the same in mojo code, we need to comment out code lines in mojo/lib/SL.pm as shown in screen shot attached.

![Selection_031](https://user-images.githubusercontent.com/13597/140689489-845858db-57ef-4069-b8ef-e359f23f470a.png)

This fixed the 'not logged in' error but then I got following error in the log.

[Mon Nov 08 06:20:20.371237 2021] [cgi:error] [pid 31201:tid 140304609158720] [client 72.255.36.21:44300] AH01215: [2021-11-08 06:20:20.37081] [10112] [error] [idiiowNh] Insufficient permissions to read '/PATH-REMOVED/htdocs/mojo/lib/SL/Model/SQL/resources/common.yml' at mojo/lib/SL/Model/SQL/Statement.pm line 41.: /PATH-REMOVED/htdocs/mojo.pl, referer: https://URL-REMOVED.ch/menu.pl?login=USER-REMOVED&action=acc_menu&path=bin/mozilla&js=1&menuids=

Then I changed permissions in ../htdocs/mojo/lib/SL/Model/GoBD/resources folder: chmod 666 *
This still resulted in error but now an ambiguous one without telling anything what is wrong. Here is the error:

[Mon Nov 08 06:24:10.511805 2021] [ssl:info] [pid 31202:tid 140304409642560] [client 72.255.36.21:44420] AH01964: Connection to child 143 established (server URL-REMOVED.ch:443)

Then I ran this command in the htdocs/mojo folder 

chmod 755 -R *

And everything seems to be working.

Regards

**Comment by sweitmann** [comment] 2021-11-08 08:49
Hi Armaghan, 

Thank you for sorting out all those obstacles. 

a.) 'Export--GoBD' feature now seems to be working. 

b.) 'Export--Preliminary VAT Return' feature needs some more attention. 

The b.) feature produces the LibreOffice Calc file, but it doesn't contain any information.

Here is an example of the LibreOffice Calc file as it comes from another server where this feature is working without issues: 
[Run_my_Accounts_Deutschland_AG_Umsatzsteuer-Voranmeldung_2021-01 (1).ods](https://github.com/ledger123/runmyaccounts/files/7495456/Run_my_Accounts_Deutschland_AG_Umsatzsteuer-Voranmeldung_2021-01.1.ods)


And here is the empty version that is currently coming from our RMA clone on kvm-1267: 
[Run_my_Accounts_Deutschland_AG_Umsatzsteuer-Voranmeldung_2021-01.ods](https://github.com/ledger123/runmyaccounts/files/7495461/Run_my_Accounts_Deutschland_AG_Umsatzsteuer-Voranmeldung_2021-01.ods)

Any ideas?

Regards

**Comment by ledger123** [comment] 2021-11-09 05:14
Hi Sebastian, Good morning.

This is fixed with commit linked to this ticket in 277_ branch. This was being caused by a perl module trying to create a temp file in the sql-ledger root folder. I have added a line to change it to '/tmp' as shown in the commit above.

Kindly test and confirm in your convenience.

Here was the error that was caused and is fixed now for record purposes:

[Tue Nov 09 05:11:29.460260 2021] [cgi:error] [pid 6012:tid 140304501962304] [client 72.255.36.21:45005] AH01215: IO error: Can't open ./oo_euEb1 for write : Permission denied : /PATH-REMOVED/htdocs/mojo.pl, referer: https://URL-REMOVED/mojo.pl/pvr/start?path=bin/mozilla&action=section_menu&level=Export--Preliminary%20VAT%20Return&login=admin&js=1

**Comment by phkroll** [comment] 2021-11-17 09:51
Hey together,

About the Auth fix. I'm not quite sure.
Actually it should be fixed in same file, but a few line below in logged_in.
There the whitelist feature is added. But as pointed out some time ago in Slack, the IP is hardcoded instead of read out of the config. So if this is changed to read the value from config and it contains the correct IP it should work without any of those mentioned changes commenting out stuff.

About the other errors.

Do I understand it correct, that all which is left for stepping stone todo is:
1. chmod 755 -R ~/sql-ledger/mojo/*
2. Maybe not needed but if there is an error: 
chmod 666 ~/sql-ledger/mojo/lib/SL/Model/GoBD/resources

And if this is done, it should work?

**Comment by ledger123** [comment] 2021-11-18 10:38
Hi Philipp,

Yes, right. In short, this is actually a permissions issue which can be sorted out by looking at apache error log whenever you get error.

Regarding hard-coded ip address, I shall fix it to read from config but it will be nice you can get it working before that. 

Regards

**Closed** 2022-06-01 13:28 UTC
Labels: Sebastian
